server:
  port: 9999

spring:
  datasource:
    username: root
    password: szw123
    url: jdbc:mysql://localhost:3306/xdb?serverTimezone=UTC

  redis:
    port: 6379
    host: localhost
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    com.szw.demo: debug
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1


  type-aliases-package: com.szw.demo.*.entity



